### ISSUE TITLE
you only offer six dataset benchmark here

### ISSUE THREAD

**Issue by GewelsJI** [ArcherFMY/sal_eval_toolbox#4]
can you provide benchmarking on the other four datasets:
SOS 
THUR
MSRA10K
SED

**Comment by ArcherFMY** [comment]
Hi, sorry for my late reply.

This will be a big program, but currently, I have something at hand.

I will update this project to include more dataset. BTW, some deep methods use THUR, MSRA10K to train their networks. So it would be unfair to compare these methods with others on these datasets.

Thanks.
