### ISSUE TITLE
Why do you use 0.1 as the threshold?

### ISSUE THREAD

**Issue by lartpang** [ArcherFMY/sal_eval_toolbox#5]
https://github.com/ArcherFMY/sal_eval_toolbox/blob/8e3837f783cea892e13a47601a1329836c7860f0/tools/Curve_BenchCode/performCalcu.m#L42

The DUTS's ground truth is not entirely binary.

Thanks....

**Comment by ArcherFMY** [comment]
The basic code is from my senior colleagues. They used this threshold to binarize the ground truth. I just tried the 0.5 as the threshold and there is no big difference when evaluating DUTS-test dataset. 

I think it is ok as long as we evaluate all algorithms using the same settings.

**Comment by lartpang** [comment]
OK, thanks!
